project:
  type: website

website:
  title: "Peter Kirwan"
  description: "Research Associate at MRC Biostatistics Unit, Cambridge"
  site-url: https://www.pkirwan.com
  repo-url: https://github.com/pkirwan/pkirwan.com
  open-graph: true
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: "About"
        href: index.qmd#about
      - text: "Survival data posts"
        href: index.qmd#blog
      - text: "Publications"
        href: index.qmd#recent-publications
      - text: "Talks"
        href: index.qmd#talks
      - text: "Contact"
        href: index.qmd#contact
    pinned: true
    toggle-position: right
    collapse-below: lg
  page-footer: 
    center:
      - href: https://www.pkirwan.com
        text: www.pkirwan.com

format:
  html:
    theme: 
      light: [cosmo, common/light_style.scss]
      dark: [cosmo, common/dark_style.scss]
    css: common/style.css
    page-layout: full
    header-includes: <link rel="stylesheet" href="/font/inter.css">
    mainfont: "Inter"
    fontsize: 1em
    respect-user-color-scheme: true
    hide-description: true
    crossrefs-hover: false

execute:
  freeze: auto